fixed_income:
  pension_monthly_amounts:
  - 0
  pension_ages:
  - 65
  pension_indexed:
  - false
  pension_survivor_fraction:
  - 0.0
  social_security_pia_amounts:
  - 0
  social_security_ages:
  - 67.0
pension_monthly_amounts:
- 0
pension_ages:
- 65
pension_indexed:
- false
pension_survivor_fraction:
- 0.0
social_security_pia_amounts:
- 0
social_security_ages:
- 67.0
social_security_trim_pct: null
social_security_trim_year: null
spia_individuals: null
spia_buy_years: null
spia_premiums: null
spia_monthly_incomes: null
spia_indexed: null
spia_survivor_fractions: null
ss_age_pair: null
