pension_monthly_amounts: null
pension_ages: null
pension_indexed: null
pension_survivor_fraction: null
social_security_pia_amounts: null
social_security_ages: null
social_security_trim_pct: null
social_security_trim_year: null
spia_individuals: null
spia_buy_years: null
spia_premiums: null
spia_monthly_incomes: null
spia_indexed: null
spia_survivor_fractions: null
ss_age_pair: null
