session_id: null
session_description: null
run_id: null
run_description: null
trial_id: null
master_seed: null
rate_seed: null
longevity_seed: null
trials_per_run: null
workers_per_run: null
worker_timeout: null
run_owl_as_subprocess: null
workers_per_run_mode: null
auto_workers_by_solver: null
auto_runtime_environment_by_solver: null
optimization_goal: null
