rates_selection:
  heirs_rate_on_tax_deferred_estate: 30.0
  dividend_rate: 1.8000000000000003
  obbba_expiration_year: 2032
  method: historical average
  to: 2020
  from: 1960
  reverse_sequence: false
  roll_sequence: 0
heirs_rate_on_tax_deferred_estate: 30.0
dividend_rate: 1.8000000000000003
obbba_expiration_year: 2032
method: historical average
from_: null
to: 2020
values: null
standard_deviations: null
correlations: null
rate_seed: null
reproducible_rates: null
reverse_sequence: false
roll_sequence: 0
bootstrap_type: null
block_size: null
shrink: null
state_tax: null
rates_seed: null
net_investment_income_tax: null
long_term_capital_gains_rate: null
from_to: null
regime: null
from: 1960
