# src/owlroost/metrics/plugins/output_metrics.py

from __future__ import annotations

from owlroost.catalog.ontology import (
    ProjectionKind,
)

from owlroost.display.specs import (
    DisplayProfile,
)

from owlroost.metrics.specs import (
    MetricFieldSpec,
)

# =========================================================
# Display Overlay Helpers
# =========================================================

#
# IMPORTANT
# =========
#
# Ontology now lives directly inside:
#
#     MetricFieldSpec
#
# via:
#
#     OntologySpec
#
# This plugin layer intentionally contains ONLY:
#
#     - registry bootstrap
#     - display overlays
#     - aggregate synthesis
#
# Long-term this file may become:
#
#     - autogenerated
#     - declarative
#     - thin bootstrap glue
#
# =========================================================


DISPLAY_PROFILES: dict[
    str,
    dict[str, DisplayProfile],
] = {
    # =====================================================
    # Timing
    # =====================================================
    "timing.elapsed_seconds": {
        "table": DisplayProfile(
            label="Elapsed\nSec",
            fmt="float2",
            content_align="right",
        ),
        "pivot": DisplayProfile(
            label="Elapsed Seconds",
            fmt="float2",
        ),
    },
    # =====================================================
    # Trial Inventory
    # =====================================================
    "trial.completed": {
        "table": DisplayProfile(
            label="Done",
            fmt="int",
            content_align="right",
        ),
        "pivot": DisplayProfile(
            label="Trials Completed",
            fmt="int",
        ),
    },
    "trial.pending": {
        "table": DisplayProfile(
            label="Pending",
            fmt="int",
            content_align="right",
        ),
        "pivot": DisplayProfile(
            label="Trials Pending",
            fmt="int",
        ),
    },
    "trial.total": {
        "table": DisplayProfile(
            label="Trials",
            fmt="int",
            content_align="right",
        ),
        "pivot": DisplayProfile(
            label="Total Trials",
            fmt="int",
        ),
    },
    "trial.completion_rate": {
        "table": DisplayProfile(
            label="Complete\n%",
            fmt="percent",
            content_align="right",
        ),
        "pivot": DisplayProfile(
            label="Completion Rate",
            fmt="percent",
        ),
    },
    # =====================================================
    # Financial Outcomes
    # =====================================================
    "financial.spending.year0.today": {
        "table": DisplayProfile(
            label="Year 0\nSpending",
            fmt="currency0",
            content_align="right",
        ),
        "pivot": DisplayProfile(
            label="Year-0 Spending",
            fmt="currency0",
        ),
    },
    "financial.spending.total.today": {
        "table": DisplayProfile(
            label="Total\nSpend",
            fmt="currency0",
            content_align="right",
        ),
        "pivot": DisplayProfile(
            label="Total Spending",
            fmt="currency0",
        ),
    },
    "financial.bequest.total.today": {
        "table": DisplayProfile(
            label="Bequest",
            fmt="currency0",
            content_align="right",
        ),
        "pivot": DisplayProfile(
            label="Terminal Bequest",
            fmt="currency0",
        ),
    },
    # =====================================================
    # Risk
    # =====================================================
    "risk.summary.overall_risk": {
        "table": DisplayProfile(
            label="Risk",
        ),
        "pivot": DisplayProfile(
            label="Overall Risk",
        ),
    },
    "risk.summary.scenario_severity": {
        "table": DisplayProfile(
            label="Scenario\nSeverity",
            fmt="float2",
            content_align="right",
        ),
        "pivot": DisplayProfile(
            label="Scenario Severity",
            fmt="float2",
        ),
    },
}

# =========================================================
# Canonical Metrics
# =========================================================

#
# IMPORTANT
# =========
#
# These are the canonical semantic metric definitions.
#
# Long-term this list should likely become:
#
#     - autogenerated
#     - coverage validated
#     - synchronized against metrics.json
#     - synthesized from builders.py
#
# =========================================================


CANONICAL_METRICS: list[
    MetricFieldSpec
] = [
    # =====================================================
    # Timing
    # =====================================================
    MetricFieldSpec(
        name="timing.elapsed_seconds",
        category="metric",
        description=(
            "Elapsed execution time "
            "for a single trial."
        ),
        owner="ROOST",
        semantic_domain="execution",
        value_origin="roost-computed",
        projection_kind="canonical",
        materialization_level="trial",
        dtype=float,
        aggregatable=True,
        default_aggregates=[
            "mean",
            "median",
            "p90",
            "max",
        ],
        profiles=DISPLAY_PROFILES.get(
            "timing.elapsed_seconds",
            {},
        ),
    ),
    # =====================================================
    # Trial Inventory
    # =====================================================
    MetricFieldSpec(
        name="trial.completed",
        category="metric",
        description=(
            "Number of completed trials."
        ),
        owner="ROOST",
        semantic_domain="execution",
        value_origin="roost-computed",
        projection_kind="canonical",
        materialization_level="run",
        dtype=int,
        aggregatable=False,
        profiles=DISPLAY_PROFILES.get(
            "trial.completed",
            {},
        ),
    ),
    MetricFieldSpec(
        name="trial.pending",
        category="metric",
        description=(
            "Number of pending trials."
        ),
        owner="ROOST",
        semantic_domain="execution",
        value_origin="roost-computed",
        projection_kind="canonical",
        materialization_level="run",
        dtype=int,
        aggregatable=False,
        profiles=DISPLAY_PROFILES.get(
            "trial.pending",
            {},
        ),
    ),
    MetricFieldSpec(
        name="trial.total",
        category="metric",
        description=(
            "Total number of trials."
        ),
        owner="ROOST",
        semantic_domain="design",
        value_origin="user-specified",
        projection_kind="canonical",
        materialization_level="run",
        dtype=int,
        aggregatable=False,
        profiles=DISPLAY_PROFILES.get(
            "trial.total",
            {},
        ),
    ),
    MetricFieldSpec(
        name="trial.completion_rate",
        category="metric",
        description=(
            "Fraction of completed trials."
        ),
        owner="ROOST",
        semantic_domain="execution",
        value_origin="roost-computed",
        projection_kind="synthetic",
        materialization_level="run",
        dtype=float,
        aggregatable=False,
        profiles=DISPLAY_PROFILES.get(
            "trial.completion_rate",
            {},
        ),
    ),
    # =====================================================
    # Financial Outcomes
    # =====================================================
    MetricFieldSpec(
        name="financial.spending.year0.today",
        category="metric",
        description=(
            "Inflation-adjusted "
            "year-0 spending."
        ),
        owner="OWL",
        semantic_domain="decision",
        value_origin="owl-computed",
        projection_kind="canonical",
        materialization_level="trial",
        dtype=float,
        aggregatable=True,
        default_aggregates=[
            "mean",
            "median",
            "p10",
            "p90",
        ],
        profiles=DISPLAY_PROFILES.get(
            "financial.spending.year0.today",
            {},
        ),
    ),
    MetricFieldSpec(
        name="financial.spending.total.today",
        category="metric",
        description=(
            "Total lifetime inflation-adjusted "
            "spending."
        ),
        owner="OWL",
        semantic_domain="decision",
        value_origin="owl-computed",
        projection_kind="canonical",
        materialization_level="trial",
        dtype=float,
        aggregatable=True,
        default_aggregates=[
            "mean",
            "median",
            "p10",
            "p90",
        ],
        profiles=DISPLAY_PROFILES.get(
            "financial.spending.total.today",
            {},
        ),
    ),
    MetricFieldSpec(
        name="financial.bequest.total.today",
        category="metric",
        description=(
            "Terminal inflation-adjusted "
            "bequest."
        ),
        owner="OWL",
        semantic_domain="decision",
        value_origin="owl-computed",
        projection_kind="canonical",
        materialization_level="trial",
        dtype=float,
        aggregatable=True,
        default_aggregates=[
            "mean",
            "median",
            "p10",
            "p90",
        ],
        profiles=DISPLAY_PROFILES.get(
            "financial.bequest.total.today",
            {},
        ),
    ),
    # =====================================================
    # Risk
    # =====================================================
    MetricFieldSpec(
        name="risk.summary.overall_risk",
        category="metric",
        description=(
            "Overall scenario risk "
            "classification."
        ),
        owner="OWL",
        semantic_domain="decision",
        value_origin="owl-computed",
        projection_kind="synthetic",
        materialization_level="trial",
        dtype=str,
        aggregatable=False,
        profiles=DISPLAY_PROFILES.get(
            "risk.summary.overall_risk",
            {},
        ),
    ),
    MetricFieldSpec(
        name="risk.summary.scenario_severity",
        category="metric",
        description=(
            "Severity score for "
            "scenario outcomes."
        ),
        owner="OWL",
        semantic_domain="decision",
        value_origin="owl-computed",
        projection_kind="synthetic",
        materialization_level="trial",
        dtype=float,
        aggregatable=True,
        default_aggregates=[
            "mean",
            "median",
            "p90",
        ],
        profiles=DISPLAY_PROFILES.get(
            "risk.summary.scenario_severity",
            {},
        ),
    ),
]

# =========================================================
# Aggregate Profile Synthesis
# =========================================================


def synthesize_aggregate_profiles(
    metric_name: str,
    aggregate_name: str,
    base_profiles: dict[
        str,
        DisplayProfile,
    ],
):
    """
    Create aggregate display profiles
    derived from canonical metric profiles.
    """

    synthesized = {}

    suffix = aggregate_name.upper()

    for (
        mode,
        profile,
    ) in base_profiles.items():
        label = (
            profile.label
            if profile.label
            else metric_name
        )

        synthesized[mode] = DisplayProfile(
            label=f"{label}\n{suffix}",
            fmt=profile.fmt,
            content_align=(
                profile.content_align
            ),
            width=profile.width,
            wrap=profile.wrap,
            visible=profile.visible,
        )

    return synthesized


# =========================================================
# Plugin
# =========================================================


class OutputMetricsPlugin:
    """
    Register canonical output metrics.

    Ontology semantics live directly
    inside MetricFieldSpec via:

        OntologySpec

    This plugin is intentionally thin.
    """

    def register(
        self,
        registry,
    ):
        # =================================================
        # Canonical Metrics
        # =================================================

        for metric in CANONICAL_METRICS:
            registry.register(metric)

        # =================================================
        # Aggregate Metrics
        # =================================================

        canonical_metrics = list(
            registry.all()
        )

        for metric in canonical_metrics:
            if not metric.aggregatable:
                continue

            for (
                aggregate_name
            ) in metric.default_aggregates:
                aggregate_metric_name = (
                    f"{metric.name}"
                    f"__{aggregate_name}"
                )

                registry.register(
                    MetricFieldSpec(
                        # ---------------------------------
                        # Identity
                        # ---------------------------------
                        name=aggregate_metric_name,
                        category="aggregate",
                        description=(
                            f"{aggregate_name} "
                            f"aggregate of "
                            f"{metric.name}"
                        ),
                        # ---------------------------------
                        # Ontology
                        # ---------------------------------
                        owner=metric.owner,
                        semantic_domain=(
                            metric.semantic_domain
                        ),
                        value_origin=(
                            metric.value_origin
                        ),
                        projection_kind="aggregate",
                        materialization_level="run",
                        # ---------------------------------
                        # Provenance
                        # ---------------------------------
                        defined_in=(
                            "metrics/plugins/"
                            "output_metrics.py"
                        ),
                        derived_from=[
                            metric.name,
                        ],
                        aggregate_function=(
                            aggregate_name
                        ),
                        # ---------------------------------
                        # Typing
                        # ---------------------------------
                        dtype=metric.dtype,
                        # ---------------------------------
                        # Aggregation
                        # ---------------------------------
                        aggregatable=False,
                        default_aggregates=[],
                        # ---------------------------------
                        # Display
                        # ---------------------------------
                        profiles=(
                            synthesize_aggregate_profiles(
                                metric_name=(
                                    metric.name
                                ),
                                aggregate_name=(
                                    aggregate_name
                                ),
                                base_profiles=(
                                    metric.profiles
                                ),
                            )
                        ),
                        # ---------------------------------
                        # Notes
                        # ---------------------------------
                        notes=(
                            "Autogenerated aggregate "
                            "metric."
                        ),
                    )
                )
