# src/owlroost/metrics/plugins/output_metrics.py
#
# Copyright (c) 2026 John Leonard
# SPDX-License-Identifier: GPL-3.0-or-later
# See LICENSE file in repository root.

"""
TODO: Document module.

Notes
-----
Describe responsibilities, ownership,
and architectural role.
"""

from __future__ import annotations

from owlroost.metrics.specs import (
    MetricSpec,
)

# =========================================================
# Canonical Metrics
# =========================================================

#
# IMPORTANT
# =========
#
# These are the canonical semantic metric
# definitions.
#
# This module intentionally owns ONLY:
#
#     - metric ontology bootstrap
#     - aggregate ontology synthesis
#
# Display overlays belong downstream
# in the display subsystem.
#
# Long-term this list may become:
#
#     - autogenerated
#     - coverage validated
#     - synchronized against metrics.json
#     - synthesized from builders.py
#
# =========================================================


CANONICAL_METRICS: list[MetricSpec] = [
    # =====================================================
    # Timing
    # =====================================================
    MetricSpec(
        name="timing.elapsed_seconds",
        category="metric",
        description=("Elapsed execution time for a single trial."),
        owner="ROOST",
        semantic_domain="execution",
        value_origin="roost-computed",
        projection_kind="canonical",
        analytic_kind="observed",
        materialization_level="trial",
        dtype=float,
        aggregatable=True,
        default_aggregates=[
            "mean",
            "median",
            "p90",
            "max",
        ],
    ),
    # =====================================================
    # Trial Inventory
    # =====================================================
    MetricSpec(
        name="trial.completed",
        category="metric",
        description=("Number of completed trials."),
        owner="ROOST",
        semantic_domain="execution",
        value_origin="roost-computed",
        projection_kind="canonical",
        analytic_kind="observed",
        materialization_level="run",
        dtype=int,
        aggregatable=False,
    ),
    MetricSpec(
        name="trial.pending",
        category="metric",
        description=("Number of pending trials."),
        owner="ROOST",
        semantic_domain="execution",
        value_origin="roost-computed",
        projection_kind="canonical",
        analytic_kind="observed",
        materialization_level="run",
        dtype=int,
        aggregatable=False,
    ),
    MetricSpec(
        name="trial.total",
        category="metric",
        description=("Total number of trials."),
        owner="ROOST",
        semantic_domain="design",
        value_origin="user-specified",
        projection_kind="canonical",
        analytic_kind="observed",
        materialization_level="run",
        dtype=int,
        aggregatable=False,
    ),
    MetricSpec(
        name="trial.completion_rate",
        category="metric",
        description=("Fraction of completed trials."),
        owner="ROOST",
        semantic_domain="execution",
        value_origin="roost-computed",
        projection_kind="synthetic",
        analytic_kind="synthetic",
        materialization_level="run",
        dtype=float,
        aggregatable=False,
    ),
    # =====================================================
    # Financial Outcomes
    # =====================================================
    MetricSpec(
        name="financial.spending.year0.today",
        category="metric",
        description=("Inflation-adjusted year-0 spending."),
        owner="OWL",
        semantic_domain="decision",
        value_origin="owl-computed",
        projection_kind="canonical",
        analytic_kind="observed",
        materialization_level="trial",
        dtype=float,
        aggregatable=True,
        default_aggregates=[
            "mean",
            "median",
            "p10",
            "p90",
        ],
    ),
    MetricSpec(
        name="financial.spending.total.today",
        category="metric",
        description=("Total lifetime inflation-adjusted spending."),
        owner="OWL",
        semantic_domain="decision",
        value_origin="owl-computed",
        projection_kind="canonical",
        analytic_kind="observed",
        materialization_level="trial",
        dtype=float,
        aggregatable=True,
        default_aggregates=[
            "mean",
            "median",
            "p10",
            "p90",
        ],
    ),
    MetricSpec(
        name="financial.bequest.total.today",
        category="metric",
        description=("Terminal inflation-adjusted bequest."),
        owner="OWL",
        semantic_domain="decision",
        value_origin="owl-computed",
        projection_kind="canonical",
        analytic_kind="observed",
        materialization_level="trial",
        dtype=float,
        aggregatable=True,
        default_aggregates=[
            "mean",
            "median",
            "p10",
            "p90",
        ],
    ),
    MetricSpec(
        name="social_security.ages",
        category="metric",
        description=("Output social security ages.  May be optimized. See withSSAges."),
        owner="OWL",
        semantic_domain="decision",
        value_origin="owl-computed",
        projection_kind="canonical",
        analytic_kind="observed",
        materialization_level="trial",
        dtype=float,
        aggregatable=True,
        default_aggregates=[
            "mean",
            "median",
            "p10",
            "p90",
        ],
    ),
    MetricSpec(
        name="social_security.optimized",
        category="metric",
        description=("Are output social_security.ages optimized? See withSSAges."),
        owner="OWL",
        semantic_domain="decision",
        value_origin="owl-computed",
        projection_kind="canonical",
        analytic_kind="observed",
        materialization_level="trial",
        dtype=bool,
        aggregatable=True,
        default_aggregates=["constant"],
    ),
    # =====================================================
    # Risk
    # =====================================================
    MetricSpec(
        name="risk.summary.overall_risk",
        category="metric",
        description=("Overall scenario risk classification."),
        owner="OWL",
        semantic_domain="decision",
        value_origin="owl-computed",
        projection_kind="synthetic",
        analytic_kind="synthetic",
        materialization_level="trial",
        dtype=str,
        aggregatable=False,
    ),
    MetricSpec(
        name="risk.summary.scenario_severity",
        category="metric",
        description=("Severity score for scenario outcomes."),
        owner="OWL",
        semantic_domain="decision",
        value_origin="owl-computed",
        projection_kind="synthetic",
        analytic_kind="synthetic",
        materialization_level="trial",
        dtype=float,
        aggregatable=True,
        default_aggregates=[
            "mean",
            "median",
            "p90",
        ],
    ),
]

# =========================================================
# Plugin
# =========================================================


class OutputMetricsPlugin:
    """
    Register canonical output metrics.

    Ontology semantics live directly
    inside MetricSpec via:

        OntologySpec

    This plugin intentionally owns ONLY:

        - metric ontology bootstrap
        - aggregate ontology synthesis

    Canonical metrics model:

        - direct runtime observations
        - synthetic analytical helpers
        - aggregate analytical reductions
    """

    def register(
        self,
        registry,
    ):
        # =================================================
        # Canonical Metrics
        # =================================================

        for metric in CANONICAL_METRICS:
            registry.register(metric)

        # =================================================
        # Aggregate Metrics
        # =================================================

        canonical_metrics = list(registry.all())

        for metric in canonical_metrics:
            if not metric.aggregatable:
                continue

            for aggregate_name in metric.default_aggregates:
                aggregate_metric_name = f"{metric.name}__{aggregate_name}"

                registry.register(
                    MetricSpec(
                        # ---------------------------------
                        # Identity
                        # ---------------------------------
                        name=aggregate_metric_name,
                        category="aggregate",
                        description=(f"{aggregate_name} aggregate of {metric.name}"),
                        # ---------------------------------
                        # Ontology
                        # ---------------------------------
                        owner=metric.owner,
                        semantic_domain=(metric.semantic_domain),
                        value_origin=(metric.value_origin),
                        projection_kind="aggregate",
                        analytic_kind="aggregate",
                        materialization_level="run",
                        # ---------------------------------
                        # Provenance
                        # ---------------------------------
                        defined_in=("metrics/plugins/output_metrics.py"),
                        derived_from=[
                            metric.name,
                        ],
                        aggregate_function=(aggregate_name),
                        # ---------------------------------
                        # Typing
                        # ---------------------------------
                        dtype=metric.dtype,
                        # ---------------------------------
                        # Aggregation
                        # ---------------------------------
                        aggregatable=False,
                        default_aggregates=[],
                        # ---------------------------------
                        # Notes
                        # ---------------------------------
                        notes=("Autogenerated aggregate metric."),
                    )
                )
