name: CI

on:
  push:
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v4

      - run: uv sync --extra dev
      - run: uv run pre-commit run --all-files
      - run: tree src/owlroost/conf
      - run: uv run pytest
